import type { Metadata } from "next";
import GovukInit from "./components/govuk/GovukInit";
import "./govuk.scss";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/assets/manifest.json",
  icons: {
    icon: [
      { url: "/assets/images/favicon.ico", sizes: "48x48" },
      {
        url: "/assets/images/favicon.svg",
        sizes: "any",
        type: "image/svg+xml",
      },
    ],
    apple: "/assets/images/govuk-icon-180.png",
    other: [
      {
        rel: "mask-icon",
        url: "/assets/images/govuk-icon-mask.svg",
        color: "#0b0c0c",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="govuk-template">
      <body className="govuk-template__body">
        <Script strategy="beforeInteractive">
          {"document.body.className += ' js-enabled' + ('noModule' in HTMLScriptElement.prototype ? ' govuk-frontend-supported' : '');"}
        </Script>
        <GovukInit />
        {children}
      </body>
    </html>
  );
}
